# 开发环境配置覆盖

# HTTP服务端口配置
http_addr: "0.0.0.0:18080"

# 开发环境特定的CORS配置 - 测试期间允许所有来源
cors_allowed:
  - "*"

# 开发环境日志级别
log_level: "debug"

# 开发环境数据库（如果需要覆盖）
# pg_dsn: "postgres://postgres:postgres@127.0.0.1:5432/iot_dev"

# 开发环境InfluxDB配置
influx_token: "dev-token"