apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: iot-data
    user: admin
    secureJsonData:
      password: password123
    jsonData:
      version: Flux
      organization: edge-gateway
      defaultBucket: iot-data
      tlsSkipVerify: true